// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-partners.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SAMPLE_PARTNERS = [
  { id: "p_001", name: "Acme Solutions", tier: "Gold", type: "Reseller", country: "TR", annualRevenue: 41e3, certifiedUsers: 4 },
  { id: "p_002", name: "Bright Systems", tier: "Silver", type: "Referral", country: "DE", annualRevenue: 12500, certifiedUsers: 2 },
  { id: "p_003", name: "Cobalt IT", tier: "Platinum", type: "Reseller", country: "UK", annualRevenue: 245e3, certifiedUsers: 11 },
  { id: "p_004", name: "DeltaWorks", tier: "Bronze", type: "Referral", country: "NL", annualRevenue: 4200, certifiedUsers: 1 }
];
var list_partners_default = defineTool({
  name: "list_partners",
  title: "List partners",
  description: "List partners in the PartnerHub portal. Supports optional tier and type filters.",
  inputSchema: {
    tier: z.enum(["Bronze", "Silver", "Gold", "Platinum"]).optional().describe("Filter by tier."),
    type: z.enum(["Reseller", "Referral"]).optional().describe("Filter by partner type."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of partners to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ tier, type, limit }) => {
    let rows = SAMPLE_PARTNERS;
    if (tier) rows = rows.filter((p) => p.tier === tier);
    if (type) rows = rows.filter((p) => p.type === type);
    if (limit) rows = rows.slice(0, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { partners: rows }
    };
  }
});

// src/lib/mcp/tools/list-deals.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var SAMPLE_DEALS = [
  { id: "d_1001", partner: "Acme Solutions", customer: "Northwind Corp", stage: "Proposal", value: 18500, currency: "USD", closeDate: "2026-08-14" },
  { id: "d_1002", partner: "Acme Solutions", customer: "Globex", stage: "Won", value: 22500, currency: "USD", closeDate: "2026-06-30" },
  { id: "d_1003", partner: "Cobalt IT", customer: "Initech", stage: "Negotiation", value: 78e3, currency: "USD", closeDate: "2026-09-01" },
  { id: "d_1004", partner: "Bright Systems", customer: "Umbrella", stage: "Qualified", value: 6500, currency: "USD", closeDate: "2026-07-20" },
  { id: "d_1005", partner: "DeltaWorks", customer: "Wayne Ent.", stage: "Lost", value: 3200, currency: "USD", closeDate: "2026-05-10" }
];
var list_deals_default = defineTool2({
  name: "list_deals",
  title: "List deals",
  description: "List deals in the pipeline. Supports optional stage and partner filters.",
  inputSchema: {
    stage: z2.enum(["Qualified", "Proposal", "Negotiation", "Won", "Lost"]).optional(),
    partner: z2.string().optional().describe("Partner name substring to filter by."),
    limit: z2.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ stage, partner, limit }) => {
    let rows = SAMPLE_DEALS;
    if (stage) rows = rows.filter((d) => d.stage === stage);
    if (partner) {
      const q = partner.toLowerCase();
      rows = rows.filter((d) => d.partner.toLowerCase().includes(q));
    }
    if (limit) rows = rows.slice(0, limit);
    const totalValue = rows.reduce((sum, d) => sum + d.value, 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ deals: rows, totalValue }, null, 2) }],
      structuredContent: { deals: rows, totalValue }
    };
  }
});

// src/lib/mcp/tools/get-dashboard-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_dashboard_summary_default = defineTool3({
  name: "get_dashboard_summary",
  title: "Get dashboard summary",
  description: "Return an aggregated snapshot of the PartnerHub admin dashboard: KPIs, pipeline stages, and top-tier distribution.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const summary = {
      kpis: {
        activePartners: 128,
        pipelineValueUsd: 1240500,
        wonThisQuarterUsd: 384200,
        avgDealSizeUsd: 12450
      },
      pipeline: [
        { stage: "Qualified", count: 42, valueUsd: 21e4 },
        { stage: "Proposal", count: 28, valueUsd: 380500 },
        { stage: "Negotiation", count: 15, valueUsd: 42e4 },
        { stage: "Won", count: 22, valueUsd: 384200 }
      ],
      tiers: { Bronze: 54, Silver: 41, Gold: 26, Platinum: 7 }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "partnerhub-mcp",
  title: "PartnerHub MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the PartnerHub B2B partner portal. Use `list_partners` to browse partners, `list_deals` to inspect the deal pipeline, and `get_dashboard_summary` for high-level KPIs.",
  tools: [list_partners_default, list_deals_default, get_dashboard_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
